package echoes.macro;

#if macro

import haxe.Exception;
import haxe.macro.ComplexTypeTools;
import haxe.macro.Expr;
import haxe.macro.Printer;
import haxe.macro.Type;
import haxe.macro.TypeTools;

using echoes.macro.ComponentStorageBuilder;
using echoes.macro.EntityTools;
using echoes.macro.MacroTools;
using haxe.EnumTools;
using haxe.macro.ComplexTypeTools;
using haxe.macro.Context;
using haxe.macro.ExprTools;
using Lambda;

/**
 * @see `echoes.Entity.build()`
 */
class EntityTemplateBuilder {
	static inline final ARGUMENTS_TAG:String = ":arguments";
	static inline final OPTIONAL_ARGUMENTS_TAG:String = ":optionalArguments";
	
	static final paramTypeCache:Map<String, ComplexType> = new Map();
	
	@:allow(echoes)
	private static function build():Array<Field> {
		Context.warning("echoes.Entity.build() is deprecated. Please install the echoes-templates Haxelib, and use echoes.Template.build() instead.", Context.currentPos());
		
		var fields:Array<Field> = Context.getBuildFields();
		
		//Information gathering
		//=====================
		
		//Get information about the `abstract` being built.
		final type:AbstractType = switch(Context.getLocalType()) {
			case TInst(_.get().kind => KAbstractImpl(_.get() => type), _):
				type;
			default:
				Context.fatalError("Entity.build() only works on abstract types.", Context.currentPos());
		};
		
		if(type.params != null && type.params.length > 0) {
			Context.fatalError('${ type.name } may not have any parameters.', Context.currentPos());
		}
		
		//Get information about parent types.
		final parents:Array<{ complexType:ComplexType, abstractType:AbstractType }> = [];
		var nextParent:Type = type.type;
		for(_ in 0...100) {
			switch(nextParent.follow()) {
				case TInst(_.get().kind => KAbstractImpl(_.get() => parentAbstract), _),
					TAbstract(_.get() => parentAbstract, _):
					parents.push({
						complexType: nextParent.toComplexType(),
						abstractType: parentAbstract
					});
					
					if(parentAbstract.name == "Entity" && parentAbstract.pack.length == 1 && parentAbstract.pack[0] == "echoes") {
						break;
					} else {
						nextParent = parentAbstract.type;
					}
				default:
					return Context.fatalError('${ type.name } must wrap echoes.Entity.', Context.currentPos());
			}
		}
		
		//Check for important fields.
		var onTemplateApplied:Bool = false;
		for(field in fields) {
			switch(field.name) {
				case "new", "_new":
					return Context.fatalError("The constructor must be generated by macro. Instead, declare an onTemplateApplied() function.", field.pos);
				case "applyTemplateTo", "applyTemplateToSelf":
					return Context.fatalError('${ field.name } is reserved. Instead, declare an onTemplateApplied() function.', field.pos);
				case "onTemplateApplied" if(field.kind.match(FFun(_.args => []))):
					onTemplateApplied = true;
				default:
			}
		}
		
		//Constructor arguments
		//---------------------
		
		/**
		 * An ordered list of parameters taken by the constructor and the
		 * "apply" functions.
		 * 
		 * Contains a temporary `storage` value, which is the identifier for the
		 * `ComponentStorage` for this type.
		 */
		final parameters:Array<FunctionArg & { storage:String }> = [];
		
		/**
		 * Arguments to pass to the super type's `applyTemplateToSelf()`.
		 */
		final superArguments:Array<Expr> = [];
		
		/**
		 * The types marked as optional that don't yet have a default value.
		 */
		final optionalValuesRemaining:Map<String, ComplexType> = [];
		
		/**
		 * Adds the given value to `parameters` and `arguments` unless it's
		 * redundant. Also adds it to `superArguments` if the flag is set.
		 */
		inline function addParams(entry:MetadataEntry, parentType:Null<AbstractType>, optional:Bool):Void {
			var params:Array<Expr> = entry.params;
			if(params == null || params.length == 0) {
				Context.warning("Expected one or more types.", entry.pos);
				params = [];
			}
			
			for(param in params) {
				var name:String = null;
				var paramType:ComplexType = null;
				switch(param.expr) {
					case EParenthesis({ expr:ECheckType(_.expr => EConst(CIdent(n)), t) }):
						name = n;
						paramType = t.followComplexType();
						
						//Since the documentation encourages using `_`, the user
						//might include it multiple times, making it unsafe to
						//use as the parameter name.
						if(name == "_") {
							name = paramType.toIdentifier(false);
						}
					default:
						final fieldChain:Null<String> = param.printFieldChain();
						if(fieldChain == null) {
							Context.fatalError("Expected component type or type check.", param.pos);
						}
						
						name = fieldChain.split(".").pop();
						name = name.charAt(0).toLowerCase() + name.substr(1);
						
						//Use the cached type if possible. If Haxe builds the
						//types in the correct order, this saves the user the
						//trouble of importing it.
						if(parentType != null) {
							paramType = paramTypeCache[parentType.module + ":" + fieldChain];
						}
						
						if(paramType == null) {
							try {
								paramType = fieldChain.getType().followMono().toComplexType();
							} catch(error:Exception) {
								if(parentType != null) {
									Context.fatalError('Could not find type $fieldChain, but ${ parentType.name } takes it as an argument. Please import it here too.', type.pos);
								} else {
									Context.fatalError('Could not find type $fieldChain. There may have been an error when generating it or a type it imports.', type.pos);
								}
							}
						}
						
						//Cache the type for later.
						if(parentType == null) {
							paramTypeCache[type.module + ":" + fieldChain] = paramType;
						}
				}
				
				final storage:String = paramType.getComponentStorageName();
				var existingName:String = null;
				for(existing in parameters) {
					if(existing.storage == storage) {
						existingName = existing.name;
						break;
					}
				}
				
				if(existingName == null) {
					existingName = name;
					parameters.push({ name: name, type: paramType, storage: storage, opt: optional });
					
					if(optional) {
						optionalValuesRemaining[storage] = paramType;
					}
				}
				
				if(parentType != null) {
					superArguments.push(macro $i{ existingName });
				}
			}
		}
		
		//Add parameters from this type.
		for(entry in type.meta.extract(ARGUMENTS_TAG)) {
			addParams(entry, null, false);
		}
		for(entry in type.meta.extract(OPTIONAL_ARGUMENTS_TAG)) {
			addParams(entry, null, true);
		}
		
		//Add inherited parameters.
		for(i => parent in parents) {
			for(entry in parent.abstractType.meta.extract(ARGUMENTS_TAG)) {
				addParams(entry, parent.abstractType, false);
			}
			
			//Don't inherit optional parameters, but do leave space for them to
			//to help the compiler parse the super call.
			if(i == 0) {
				for(entry in parent.abstractType.meta.extract(OPTIONAL_ARGUMENTS_TAG)) {
					if(entry.params != null) {
						for(_ in entry.params) {
							superArguments.push(macro null);
						}
					}
					
					//addParams(entry, parent.abstractType, true);
				}
			}
		}
		
		//Modifications
		//=============
		
		//Forward all parent fields.
		if(!type.meta.has(":forward")) {
			type.meta.add(":forward", [], Context.currentPos());
		}
		
		//Allow converting to all parent types.
		for(parent in parents) {
			final name:String = "to" + parent.abstractType.name;
			final parentType:ComplexType = parent.complexType;
			fields.pushFields(macro class ToParent {
				/**
				 * Caution: in C++, this converts `null` to `0`. Specifically,
				 * it generates the code `(int) entity` instead of `entity`.
				 * Tweaks like `Null<$parentType>` have no effect on this
				 * generated code.
				 */
				@:to private inline function $name():$parentType {
					return this;
				}
			});
		}
		
		//Process the component variables.
		final knownComponents:Array<FunctionArg> = [];
		for(field in fields) {
			if(field.access != null && field.access.contains(AStatic)) {
				continue;
			}
			
			if(field.access != null && field.access.contains(AFinal)) {
				Context.error("Components cannot have the final keyword.", field.pos);
			}
			
			//Parse the field.
			var componentType:Null<ComplexType>;
			var expr:Null<Expr>;
			switch(field.kind) {
				case FVar(t, e):
					componentType = t;
					expr = e;
				default:
					continue;
			}
			
			//Infer the component type, if not explicitly specified.
			if(componentType == null) {
				if(expr != null) {
					try {
						componentType = expr.parseComponentType().toComplexType();
					} catch(e:Exception) {
					}
				}
				
				if(componentType == null) {
					Context.fatalError('${ field.name } requires a type.', field.pos);
					continue;
				}
			} else {
				//Fully qualify the type to avoid "not found" errors.
				componentType = componentType.toType().toComplexType();
			}
			
			//Record the initial/default value.
			if(expr != null) {
				knownComponents.push({
					name: switch(componentType) {
						case TPath({ name: name, sub: null }):
							name;
						case TPath({ sub: sub }):
							sub;
						default:
							new Printer().printComplexType(componentType);
					},
					type: componentType,
					value: switch(expr) {
						case macro null:
							null;
						default:
							macro @:pos(expr.pos) ($expr:$componentType);
					}
				});
				
				//Check for incompatabilities with the metadata. (We could also
				//update the metadata to make it match, but since macro order is
				//unspecified, a child type may have already been built using
				//the wrong metadata.)
				final storage:String = componentType.getComponentStorageName();
				final parameter:FunctionArg = parameters.find(p -> p.storage == storage);
				if(parameter != null) {
					if(parameter.opt) {
						optionalValuesRemaining.remove(storage);
					} else {
						Context.fatalError('Components listed in `$ARGUMENTS_TAG` can\'t have default values. '
							+ 'Consider adding this to `$OPTIONAL_ARGUMENTS_TAG` instead.', field.pos);
					}
				}
			}
			
			//Check for reserved types.
			switch(componentType) {
				case macro:Entity, macro:echoes.Entity:
					Context.fatalError("Entity is reserved. Consider using a typedef, abstract, or Int", field.pos);
				case macro:Float, macro:StdTypes.Float:
					Context.fatalError("Float is reserved for lengths of time. Consider using a typedef or abstract", field.pos);
				default:
			}
			
			//Convert the field to a property, and remove the expression.
			field.kind = FProp("get", "set", macro:Null<$componentType>, null);
			
			final getter:String = "get_" + field.name;
			final setter:String = "set_" + field.name;
			
			fields.pushFields(macro class Accessors {
				private inline function $getter():Null<$componentType> {
					return this.get((_:$componentType));
				}
				
				private inline function $setter(value:Null<$componentType>):Null<$componentType> {
					this.add(value);
					return value;
				}
			});
		}
		
		if(!optionalValuesRemaining.empty()) {
			final missing:Array<String> = [for(type in optionalValuesRemaining)
				new Printer().printComplexType(type)];
			final s:String = missing.length == 1 ? "" : "s";
			
			Context.fatalError('Missing default value$s for the following component type$s: '
				+ missing.join(", "), Context.currentPos());
		}
		
		//"Apply" functions
		//-----------------
		
		/**
		 * An ordered list of parameters taken by the constructor and the
		 * "apply" functions. This version no longer exposes `storage`.
		 */
		final parameters:Array<FunctionArg> = [for(p in parameters) p];
		
		/**
		 * Adds `parameters` to each function in the given type definition, then
		 * inserts those functions at the beginning of `fields`, in order.
		 */
		inline function addFunctions(definition:TypeDefinition):Void {
			for(field in definition.fields) {
				switch(field.kind) {
					case FFun(f):
						f.args = f.args.concat(parameters);
					default:
						Context.fatalError("Not a function.", field.pos);
				}
			}
			
			//Insert the new fields first, so that if there's a name conflict,
			//Haxe will flag the user's version.
			fields = definition.fields.concat(fields);
		}
		
		//Add the constructor and `applyTemplateTo()`.
		final templateType:ComplexType = TPath({ pack: [], name: type.name });
		final arguments:Array<Expr> = [for(p in parameters) macro $i{ p.name }];
		addFunctions(macro class Constructor {
			public static inline function applyTemplateTo(entity:echoes.Entity):$templateType {
				(cast entity:$templateType).applyTemplateToSelf($a{ arguments });
				return cast entity;
			}
			
			public inline function new() {
				this = cast new echoes.Entity();
				applyTemplateToSelf($a{ arguments });
			}
		});
		fields[0].doc = 'Converts the given entity to `${ type.name }` by '
			+ "adding any missing components.";
		
		//Prepare the `applyTemplateToSelf()` function. Set the components in
		//order of priority: values passed by the user, then known values, then
		//inherited values.
		final applyToSelfExprs:Array<Expr> = [];
		for(parameter in parameters) {
			applyToSelfExprs.push(macro this.addIfMissing($i{ parameter.name }));
		}
		for(component in knownComponents) {
			if(component.value != null) {
				applyToSelfExprs.push(macro this.addIfMissing(${ component.value }));
			}
		}
		if(parents.length > 1) {
			applyToSelfExprs.push(macro @:privateAccess this.applyTemplateToSelf($a{ superArguments }));
		}
		if(onTemplateApplied) {
			applyToSelfExprs.push(macro onTemplateApplied());
		}
		
		//Add `applyTemplateToSelf()`; it must not be static because
		//`knownComponents` may refer to instance properties or functions.
		addFunctions(macro class ApplyToSelf {
			@:noCompletion private function applyTemplateToSelf():Void $b{ applyToSelfExprs }
		});
		
		//"Remove" functions
		//------------------
		
		final removeFromSelfExprs:Array<Expr> = [];
		for(component in knownComponents) {
			//TODO: communicate that `remove` is reserved.
			final type:ComplexType = component.type;
			removeFromSelfExprs.push(macro this.remove((_:$type)));
		}
		if(parents.length > 1) {
			removeFromSelfExprs.push(macro if(recursive) @:privateAccess this.removeTemplateFromSelf(true));
		}
		
		fields = (macro class RemoveTemplate {
			@:noCompletion public static inline function removeTemplateFrom(entity:echoes.Entity, ?recursive:Bool = false):echoes.Entity {
				(cast entity:$templateType).removeTemplateFromSelf(${ parents.length > 1 ? macro recursive : macro false });
				return cast entity;
			}
			
			@:noCompletion private function removeTemplateFromSelf(recursive:Bool):Void $b{ removeFromSelfExprs }
		}).fields.concat(fields);
		
		if(parents.length <= 1) {
			switch(fields[0].kind) {
				case FFun(f):
					f.args.pop();
				default:
			}
		}
		
		final parentNames:Array<String> = [for(i in 0...(parents.length - 1))
			"`" + parents[i].abstractType.name + "`"
		];
		if(parentNames.length > 2) {
			parentNames.push("and " + parentNames.pop());
		}
		fields[0].doc =
			(knownComponents.length == 1
				? 'Removes `${ new Printer().printComplexType(knownComponents[0].type) }`'
				: 'Removes `${ type.name }`\'s ${ knownComponents.length } components')
			+ " from the given entity.\n\nCaution: this feature is experimental, and may be subject to change."
			+ (parents.length > 1 ? '\n@param recursive Also removes components inherited from ${ parentNames.join(", ") }.' : "");
		
		return fields;
	}
}

#end
